INSERT INTO clients (
    conseiller_id,
    numero_client,
    statut,
    -- Titulaire 1 - Identité
    t1_civilite,
    t1_nom,
    t1_nom_jeune_fille,
    t1_prenom,
    t1_date_naissance,
    t1_lieu_naissance,
    t1_nationalite,
    t1_adresse,
    t1_email,
    t1_telephone,
    t1_us_person,
    t1_regime_protection_juridique,
    t1_residence_fiscale,
    -- Titulaire 1 - Profession
    t1_profession,
    t1_chef_entreprise,
    t1_entreprise_denomination,
    t1_entreprise_forme_juridique,
    t1_entreprise_siege_social,
    -- Titulaire 2 - Identité
    t2_civilite,
    t2_nom,
    t2_nom_jeune_fille,
    t2_prenom,
    t2_date_naissance,
    t2_lieu_naissance,
    t2_nationalite,
    t2_adresse,
    t2_email,
    t2_telephone,
    t2_us_person,
    t2_regime_protection_juridique,
    t2_residence_fiscale,
    -- Titulaire 2 - Profession
    t2_profession,
    -- Situation familiale
    situation_familiale,
    date_mariage,
    contrat_mariage,
    regime_matrimonial,
    donation_entre_epoux,
    donation_entre_epoux_date,
    donation_entre_epoux_montant,
    donation_enfants,
    nombre_enfants,
    nombre_enfants_charge,
    enfants,
    -- Situation financière
    revenus_annuels_foyer,
    patrimoine_global,
    charges_annuelles_pourcent,
    charges_annuelles_montant,
    capacite_epargne_mensuelle,
    impot_revenu,
    impot_fortune_immobiliere,
    patrimoine_financier_pourcent,
    patrimoine_immobilier_pourcent,
    patrimoine_professionnel_pourcent,
    patrimoine_autres_pourcent,
    -- Patrimoine détaillé
    patrimoine_financier,
    patrimoine_immobilier,
    patrimoine_professionnel,
    patrimoine_emprunts,
    patrimoine_revenus,
    patrimoine_charges,
    -- Origine des fonds
    origine_fonds_nature,
    origine_fonds_montant_prevu,
    origine_economique_revenus,
    origine_economique_epargne,
    origine_economique_heritage,
    origine_economique_cession_pro,
    origine_economique_cession_immo,
    origine_fonds_provenance_etablissement,
    -- KYC Produits
    kyc_monetaires_detention,
    kyc_monetaires_operations,
    kyc_monetaires_duree,
    kyc_monetaires_volume,
    kyc_monetaires_q1,
    kyc_monetaires_q2,
    kyc_obligations_detention,
    kyc_obligations_operations,
    kyc_obligations_duree,
    kyc_obligations_volume,
    kyc_obligations_q1,
    kyc_obligations_q2,
    kyc_actions_detention,
    kyc_actions_operations,
    kyc_actions_duree,
    kyc_actions_volume,
    kyc_actions_q1,
    kyc_actions_q2,
    kyc_scpi_detention,
    kyc_scpi_operations,
    kyc_scpi_duree,
    kyc_scpi_volume,
    kyc_scpi_q1,
    kyc_scpi_q2,
    kyc_pe_detention,
    kyc_etf_detention,
    kyc_etf_operations,
    kyc_etf_duree,
    kyc_etf_volume,
    kyc_portefeuille_mandat,
    kyc_portefeuille_gestion_personnelle,
    kyc_portefeuille_gestion_conseiller,
    kyc_culture_presse_financiere,
    kyc_culture_suivi_bourse,
    kyc_culture_releves_bancaires,
    -- Profil de risque
    objectifs_investissement,
    horizon_placement,
    tolerance_risque,
    pertes_maximales_acceptables,
    experience_perte,
    experience_perte_niveau,
    reaction_perte,
    reaction_gain,
    liquidite_importante,
    pourcentage_patrimoine_investi,
    profil_risque_calcule,
    profil_risque_score,
    profil_risque_date_calcul,
    -- ESG
    durabilite_souhait,
    durabilite_niveau_preference,
    durabilite_importance_environnement,
    durabilite_importance_social,
    durabilite_importance_gouvernance,
    durabilite_investissement_impact,
    durabilite_investissement_solidaire,
    durabilite_prise_compte_pai,
    durabilite_confirmation,
    -- LCB-FT
    lcb_ft_niveau_risque,
    lcb_ft_ppe,
    lcb_ft_ppe_famille,
    lcb_ft_gel_avoirs_verifie,
    lcb_ft_gel_avoirs_date_verification
) VALUES (
    '11111111-1111-1111-1111-111111111111',
    'CLI-2025-0042',
    'client_actif',
    -- T1 Identité
    'Monsieur',
    'TARAVAO',
    NULL,
    'Tearii',
    '1978-05-15',
    'Papeete, Tahiti',
    'Française',
    '42 Avenue Pouvanaa a Oopa, Pirae 98716, Tahiti',
    'tearii.taravao@mail.pf',
    '+689 87 42 15 78',
    false,
    false,
    'France',
    -- T1 Profession
    'Chef d''entreprise',
    true,
    'TARAVAO PERLES SARL',
    'SARL',
    '15 Rue du Port, Papeete 98714, Tahiti',
    -- T2 Identité
    'Madame',
    'TARAVAO',
    'TEARIKI',
    'Hina',
    '1982-08-22',
    'Moorea, Polynésie française',
    'Française',
    '42 Avenue Pouvanaa a Oopa, Pirae 98716, Tahiti',
    'hina.taravao@mail.pf',
    '+689 87 45 63 21',
    false,
    false,
    'France',
    -- T2 Profession
    'Cadre bancaire',
    -- Situation familiale
    'Marié(e)',
    '2005-06-18',
    true,
    'Séparation de biens',
    true,
    '2020-03-15',
    500000.00,
    true,
    3,
    1,
    '[{"prenom": "Maui", "age": 18, "a_charge": false}, {"prenom": "Vaitiare", "age": 15, "a_charge": true}, {"prenom": "Teva", "age": 10, "a_charge": false}]'::jsonb,
    -- Situation financière
    '150001-500000',
    '1000001-5000000',
    25.00,
    62500.00,
    5000.00,
    true,
    false,
    35.00,
    45.00,
    15.00,
    5.00,
    -- Patrimoine détaillé
    '[{"type": "Compte-titres", "etablissement": "Banque de Tahiti", "valeur": 350000}, {"type": "Assurance-vie", "etablissement": "AG2R", "valeur": 420000}, {"type": "PEA", "etablissement": "Banque de Polynésie", "valeur": 85000}]'::jsonb,
    '[{"type": "Résidence principale", "localisation": "Pirae, Tahiti", "valeur": 850000, "emprunt": 150000}, {"type": "Investissement locatif", "localisation": "Papeete, Tahiti", "valeur": 320000, "emprunt": 0}]'::jsonb,
    '[{"type": "Parts sociales", "societe": "TARAVAO PERLES SARL", "valeur": 380000}]'::jsonb,
    '[{"type": "Crédit immobilier", "etablissement": "Banque de Tahiti", "montant_restant": 150000, "mensualite": 1800, "fin": "2032-06"}]'::jsonb,
    '[{"type": "Salaire T1", "montant_annuel": 120000}, {"type": "Salaire T2", "montant_annuel": 85000}, {"type": "Revenus locatifs", "montant_annuel": 18000}, {"type": "Dividendes", "montant_annuel": 25000}]'::jsonb,
    '[{"type": "Charges courantes", "montant_annuel": 36000}, {"type": "Crédit immobilier", "montant_annuel": 21600}, {"type": "Impôts", "montant_annuel": 48000}]'::jsonb,
    -- Origine des fonds
    'Épargne régulière',
    100000.00,
    true,
    true,
    false,
    false,
    false,
    'Banque de Tahiti',
    -- KYC Produits
    true, 'Plus de 50', 'Plus de 10 ans', '50 000 - 100 000 €', 'Bonne', 'Bonne',
    true, '10 à 50', '5 à 10 ans', '100 000 - 500 000 €', 'Bonne', 'Moyenne',
    true, 'Plus de 50', 'Plus de 10 ans', '100 000 - 500 000 €', 'Bonne', 'Bonne',
    true, '1 à 10', '3 à 5 ans', '50 000 - 100 000 €', 'Moyenne', 'Moyenne',
    false,
    true, '10 à 50', '3 à 5 ans', '50 000 - 100 000 €',
    true,
    true,
    true,
    true,
    true,
    true,
    -- Profil de risque
    'Constitution d''un patrimoine diversifié et transmission',
    '>8ans',
    'Équilibré',
    '15-25%',
    true,
    '10-20%',
    'J''attends que ça remonte',
    'Je sécurise une partie des gains',
    true,
    '30-50%',
    'Equilibré',
    55,
    NOW(),
    -- ESG
    true,
    'Modéré',
    7,
    6,
    8,
    true,
    false,
    'Oui',
    true,
    -- LCB-FT
    'Standard',
    false,
    false,
    true,
    '2024-11-15'
) RETURNING id, numero_client, t1_nom, t1_prenom;
